name: Build and publish

on:
  schedule:
    - cron: "30 01/24 * * *"
  workflow_dispatch:

jobs:
  build_pages:
    name: Publish Edition as GitHub Pages Website
    runs-on: ubuntu-latest
    env:
      NO_LIMIT: nolimit
      R_USER: ${{secrets.R_USER}}
      R_ENDPOINT_V: ${{secrets.R_ENDPOINT_V}}
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: pip
      run: pip install -r requirements.txt
    - name: xslt
      run: ./dl_saxon_and_transform.sh
    - name: triggify 
      run: |
        python scripts/triggify.py
    - name: build
      run: ./build.sh
    - name: create inverse triples
      run: |
        python scripts/owl_inverse_props.py
    - name: Create Pages
      run: |
        ./create_pages.sh
    - name: Deploy
      run: |
        ./update_graph.sh
    - name: GH Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./html
